openai:
  model: gpt-3.5-turbo
  temperature: 0.7

discord:
  allowed_user_id: 123456789012345678
  command_prefix: "!"

reminder:
  check_interval: 60

database:
  path: "jun_assistant.db"

timezone: "Asia/Tokyo"

logging:
  level: INFO
  file: "junbot.log"
